spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: SA
    password:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/booking
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: info