spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: SA
    password:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
  jpa:
    open-in-view: false
    show-sql: true
    hibernate.hbm2ddl.auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
